### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by br0k3n** [desandro/imagesloaded#177]
Hi guys, we're using imagesloaded adding these lines of code at the beginning:

(function($) {
    'use strict';

CODE

}(jQuery))

But when we use them (to work in strict mode) we obtain many undefined errors.

How can we fix it?

Thanks

br0k3n

**Comment by desandro** [comment]
Hi there, can you provide what kind of errors you are seeing?

**Comment by br0k3n** [comment]
Sure, here's the first:

Uncaught TypeError: undefined is not a function       imagesloaded.pkgd.min.js?ver=4.1:684

and at this line there is:

ImagesLoaded.prototype = new EventEmitter();

Thanks so much

**Comment by desandro** [comment]
Can you provide a live URL? If you are using `imagesloaded.pkgd.min.js` then EventEmitter should be available.

**Comment by br0k3n** [comment]
Sure:

http://goo.gl/UpCOQx

Thanks :)

**Comment by desandro** [comment]
Thanks. Looks like your version of `imagesloaded.pkgd.min.js` has adding the `(function($){...})(jQuery)`, which is setting `this` to be `jQuery`. This is causing the error. I recommend using the original version of [imagesloaded.pkgd.js](https://github.com/desandro/imagesloaded/blob/v3.1.8/imagesloaded.pkgd.js) rather than this modification.
