### ISSUE TITLE
Proposal: make child img selector overridable

### ISSUE THREAD

**Issue by sampeka** [desandro/imagesloaded#219]
At the moment, imagesLoaded just selects all `img` tags that are children of the elements passed to it. Sometimes you may want to limit which images you are waiting on to a subset of the images. 

This wouldn't require much work, just make `selector` or `imgSelector` an option to be passed to imagesLoaded. Then change the following line to use it:

https://github.com/desandro/imagesloaded/blob/master/imagesloaded.js#L145

**Comment by desandro** [comment]
Good point. You can actually trigger `imagesLoaded` with a selector string

```
// jQuery
$('#container img.selector').imagesLoaded

// vanilla JS
imagesLoaded('#container img.selector')
```

I need to add this point to the docs.

**Comment by shmag18** [comment]
Hey would it be a bad idea for me to try to make this work for a specific css selector? I'm trying to get this working on divs....

**Comment by desandro** [comment]
@shmag18 Could you elaborate on what you are trying to do? Or better yet, provide a **Reduced test case**. See [Submitting Issues guidelines](https://github.com/desandro/imagesloaded/blob/master/contributing.md)

**Comment by shmag18** [comment]
Hi sorry a little new to this. I'm just trying to get imagesloaded to work on specific divs instead of images on my site. I am adding new divs with rails, and masonry works pretty well, however sometimes there are some divs overlapping other divs. When I resize the window all the divs move into the perfect place. After doing some research on this I found I should be using imagesloaded, but it didn't work on the divs. 

I'm just wondering if it's ok to change the line that sampeka mentioned above to the specific selector of my divs that are being added. I tried it and it works for the most part but a) there is still some overlap when refreshing the page or going to the page directly (as opposed to clicking on a link on my site) and b) there is some strange error logged to the console, something like ...assets/undefined 404 not found.

Not sure this is the right place to be discussing this but any advice would be appreciated tremendously. Thanks!
