### ISSUE TITLE
QTWeb - 'undefined' is not a function (evaluating 'this.check()')

### ISSUE THREAD

**Issue by ImranBug** [desandro/imagesloaded#230]
I am using [Qt Web Browser ](http://www.qtweb.net/) for testing mobile and old browsers. But it keeps giving me this error: 

`TypeError: 'undefined' is not a function (evaluating 'this.check()')`

Would really appreciate if you can help me resolve this.

**Comment by desandro** [comment]
Thanks for reporting this issue. I hadn't heard of this browser before. [QTWeb Browser isn't even listed in the caniuse browser usage table](http://caniuse.com/usage-table).  Sorry, but imagesLoaded v4 cannot officially support this browser.

I believe this issue is that this browser does not support Function.prototype.bind. You may want to try [imagesLoaded v3](http://imagesloaded.desandro.com/v3/) which has older browser support.

**Comment by ImranBug** [comment]
:+1:  Solved using v3 version.

90% of the time QTWeb is able to mimic issues that occur on mac, tablets and mobile that makes it easier to count on the compatibility of my code without actually having the access to test on different platforms.

Of course consumers don't use this browser so it's fair not to add support for it.
